"""empty message

Revision ID: 504f5d4564e0
Revises: 31ea09cc95f0
Create Date: 2021-06-28 19:43:49.397802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '504f5d4564e0'
down_revision = '31ea09cc95f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_constraint('request_ibfk_5', type_='foreignkey')
        batch_op.drop_column('type_foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_foreignkey', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('request_ibfk_5', 'type', ['type_foreignkey'], ['id'])

    # ### end Alembic commands ###
