"""empty message

Revision ID: 6156df22f756
Revises: 
Create Date: 2021-06-24 14:02:39.076163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6156df22f756'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('user_foreignkey',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('group_foreignkey',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'state', ['state_foreignkey'], ['id'])
        batch_op.create_foreign_key(None, 'type', ['type_foreignkey'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('group_foreignkey',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_foreignkey',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
