"""empty message

Revision ID: 79dc300741b3
Revises: abdafdf57b0c
Create Date: 2021-06-28 17:32:33.767384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79dc300741b3'
down_revision = 'abdafdf57b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('call', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('request_foreignkey', sa.Integer(), nullable=True))
        batch_op.alter_column('counselor_foreignkey',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('fk_payment_user_foreignkey_user', type_='foreignkey')
        batch_op.drop_constraint('fk_payment_counselor_foreignkey_counselor', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['counselor_foreignkey'], ['id'])
        batch_op.create_foreign_key(None, 'request', ['request_foreignkey'], ['id'])
        batch_op.drop_column('user_foreignkey')

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_constraint('fk_request_payment_foreignkey_payment', type_='foreignkey')
        batch_op.drop_column('payment_foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_foreignkey', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_request_payment_foreignkey_payment', 'payment', ['payment_foreignkey'], ['id'])

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_foreignkey', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_payment_counselor_foreignkey_counselor', 'counselor', ['counselor_foreignkey'], ['id'])
        batch_op.create_foreign_key('fk_payment_user_foreignkey_user', 'user', ['user_foreignkey'], ['id'])
        batch_op.alter_column('counselor_foreignkey',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('request_foreignkey')
        batch_op.drop_column('call')

    # ### end Alembic commands ###
